version: "3.9"

services:
  app:
    image: eclipse-temurin:23-jre
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./adaptix_bot.jar:/app/adaptix_bot.jar:ro          # jar
      - ./app.properties:/app/config/app.properties:ro     # конфиг
    command: ["java", "-XX:+UseContainerSupport", "-Xmx1g", "-jar", "/app/adaptix_bot.jar"]