version: "3.9"

services:
  app:
    image: eclipse-temurin:17-jre
    network_mode: host          # ← контейнер = хостовая сеть
    restart: unless-stopped
    ports:
      - "8080:8080"             # метрики (опционально)
    volumes:
      - ./app.properties:/app/config/app.properties:ro
      - ./adaptix_bot.jar:/app/adaptix_bot.jar:ro
    command: ["java","-XX:+UseContainerSupport","-Xmx1g","-jar","/app/adaptix_bot.jar"]